x = int(input())
y = x + 1
z = y + 1
print(x)
print(y)
print(z)
print()
x = int(input())
y = int(input())
z = int(input())
print(x + y + z)
print()
a = int(input())
v = a * a * a
s = 6 * (a * a)
print('Объем', v, sep=' = ')
print('Площадь полной поверхности', s, sep=' = ')
print()
a = int(input())
b = int(input())
f = 3 * ((a + b) * (a + b) * (a + b)) + 275 * b * b - 127 * a - 41
print(f)
pint()
x = int(input())
print('Следующее за числом', x, 'число:', x + 1)
print('Для числа', x, 'предыдущее число:', x - 1)
print()
price_monitor = int(input())
price_sysеуь_unit = int(input())
price_keyboard = int(input())
price_mouse = int(input())
print((price_monitor + price_sysеуь_unit + price_keyboard + price_mouse) * 3)
print()
x = int(input())
y = int(input())
print(x, '+', y, '=', x + y)
print(x, '-', y, '=', x - y)
print(x, '*', y, '=', x * y)
print()
a1 = int(input())
d = int(input())
n = int(input())
print(a1 + d * (n - 1))
print()
x = int(input())
print(x, 2 * x, 3 * x, 4 * x, 5 * x, sep='---')
