print('Mercury', 'Venus', sep='*', end='!')
print('Mars', 'Jupiter', sep='**', end='?')
print()
print('I', 'like', 'Python', sep='***')
print()
end = input()
line1 = input()
line2 = input()
line3 = input()
print(line1, end=end)
print(line2, end=end)
print(line3)
print()
name = input()
print('Привет,', name, end='!')