print('Здравствуй, мир!')
print()
print('4', '8', '15', '16', '23', '42')
print()
print('4')
print('8')
print('15')
print('16')
print('23')
print('42')
print()
print('*')
print('**')
print('***')
print('****')
print('*****')
print('******')
print('*******')
print()
name = input()
print('Привет,', name)
print()
champion = input()
print(champion, '- чемпион!')
print()
line1 = input()
line2 = input()
line3 = input()
print(line1)
print(line2)
print(line3)
print()
line1 = input()
line2 = input()
line3 = input()
print(line3)
print(line2)
print(line1)
print()