print('*****************')
print('*               *')
print('*               *')
print('*****************')
print()
a = int(input())
b = int(input())
print('Квадрат суммы', a, 'и', b, 'равен', (a + b) ** 2)
print('Сумма квадратов', a, 'и', b, 'равна', a ** 2 + b ** 2)
print()
a = int(input())
b = int(input())
c = int(input())
d = int(input())
print(a ** b + c ** d)
print()
n = int(input())
nn = n * 10 + n
nnn = n * 100 + n * 10 + n
print(n + nn + nnn)